#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 106
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 82
#define ALIAS_COUNT 0
#define TOKEN_COUNT 49
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5

enum {
  anon_sym_ = 1,
  sym__format = 2,
  anon_sym_SEMI_SEMI = 3,
  anon_sym_LF = 4,
  anon_sym_LPAREN_SEMI = 5,
  anon_sym_SEMI_RPAREN = 6,
  aux_sym__blockchar_token1 = 7,
  aux_sym__blockchar_token2 = 8,
  aux_sym__blockchar_token3 = 9,
  anon_sym_func = 10,
  anon_sym_LPAREN = 11,
  anon_sym_module = 12,
  anon_sym_param = 13,
  anon_sym_result = 14,
  anon_sym_RPAREN = 15,
  anon_sym_type = 16,
  sym__sign = 17,
  sym__digit = 18,
  sym__hexdigit = 19,
  anon_sym__ = 20,
  anon_sym_DOT = 21,
  aux_sym__float_token1 = 22,
  aux_sym__hexfloat_token1 = 23,
  anon_sym_DQUOTE = 24,
  anon_sym_BSLASH = 25,
  aux_sym__stringchar_token1 = 26,
  anon_sym_RBRACE = 27,
  aux_sym__char_token1 = 28,
  sym__ascii = 29,
  sym__asciiline = 30,
  sym__utf8cont = 31,
  aux_sym__utf8enc_token1 = 32,
  aux_sym__utf8enc_token2 = 33,
  aux_sym__utf8enc_token3 = 34,
  aux_sym__utf8enc_token4 = 35,
  aux_sym__utf8enc_token5 = 36,
  aux_sym__utf8enc_token6 = 37,
  aux_sym__utf8enc_token7 = 38,
  aux_sym__utf8enc_token8 = 39,
  aux_sym__utf8enc_token9 = 40,
  aux_sym__utf8enc_token10 = 41,
  aux_sym__utf8enc_token11 = 42,
  anon_sym_DOLLAR = 43,
  sym__idchar = 44,
  anon_sym_i32 = 45,
  anon_sym_i64 = 46,
  anon_sym_f32 = 47,
  anon_sym_f64 = 48,
  sym_start = 49,
  sym__space = 50,
  sym__comment = 51,
  sym_linecomment = 52,
  sym__linechar = 53,
  sym_blockcomment = 54,
  sym__blockchar = 55,
  sym__FUNC = 56,
  sym__LPAR = 57,
  sym__MODULE = 58,
  sym__PARAM = 59,
  sym__RESULT = 60,
  sym__RPAR = 61,
  sym__TYPE = 62,
  sym__utf8enc = 63,
  sym__utf8line = 64,
  sym__id = 65,
  sym_id = 66,
  sym_valtype = 67,
  sym_functype = 68,
  sym_param = 69,
  sym_result = 70,
  sym_type = 71,
  sym_module = 72,
  sym_modulefield = 73,
  aux_sym_start_repeat1 = 74,
  aux_sym_linecomment_repeat1 = 75,
  aux_sym_blockcomment_repeat1 = 76,
  aux_sym__id_repeat1 = 77,
  aux_sym_functype_repeat1 = 78,
  aux_sym_functype_repeat2 = 79,
  aux_sym_param_repeat1 = 80,
  aux_sym_module_repeat1 = 81,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = " ",
  [sym__format] = "_format",
  [anon_sym_SEMI_SEMI] = ";;",
  [anon_sym_LF] = "\n",
  [anon_sym_LPAREN_SEMI] = "(;",
  [anon_sym_SEMI_RPAREN] = ";)",
  [aux_sym__blockchar_token1] = "_blockchar_token1",
  [aux_sym__blockchar_token2] = "_blockchar_token2",
  [aux_sym__blockchar_token3] = "_blockchar_token3",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_module] = "module",
  [anon_sym_param] = "param",
  [anon_sym_result] = "result",
  [anon_sym_RPAREN] = ")",
  [anon_sym_type] = "type",
  [sym__sign] = "_sign",
  [sym__digit] = "_digit",
  [sym__hexdigit] = "_hexdigit",
  [anon_sym__] = "_",
  [anon_sym_DOT] = ".",
  [aux_sym__float_token1] = "_float_token1",
  [aux_sym__hexfloat_token1] = "_hexfloat_token1",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH] = "\\",
  [aux_sym__stringchar_token1] = "_stringchar_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym__char_token1] = "_char_token1",
  [sym__ascii] = "_ascii",
  [sym__asciiline] = "_asciiline",
  [sym__utf8cont] = "_utf8cont",
  [aux_sym__utf8enc_token1] = "_utf8enc_token1",
  [aux_sym__utf8enc_token2] = "_utf8enc_token2",
  [aux_sym__utf8enc_token3] = "_utf8enc_token3",
  [aux_sym__utf8enc_token4] = "_utf8enc_token4",
  [aux_sym__utf8enc_token5] = "_utf8enc_token5",
  [aux_sym__utf8enc_token6] = "_utf8enc_token6",
  [aux_sym__utf8enc_token7] = "_utf8enc_token7",
  [aux_sym__utf8enc_token8] = "_utf8enc_token8",
  [aux_sym__utf8enc_token9] = "_utf8enc_token9",
  [aux_sym__utf8enc_token10] = "_utf8enc_token10",
  [aux_sym__utf8enc_token11] = "_utf8enc_token11",
  [anon_sym_DOLLAR] = "$",
  [sym__idchar] = "_idchar",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [sym_start] = "start",
  [sym__space] = "_space",
  [sym__comment] = "_comment",
  [sym_linecomment] = "linecomment",
  [sym__linechar] = "_linechar",
  [sym_blockcomment] = "blockcomment",
  [sym__blockchar] = "_blockchar",
  [sym__FUNC] = "_FUNC",
  [sym__LPAR] = "_LPAR",
  [sym__MODULE] = "_MODULE",
  [sym__PARAM] = "_PARAM",
  [sym__RESULT] = "_RESULT",
  [sym__RPAR] = "_RPAR",
  [sym__TYPE] = "_TYPE",
  [sym__utf8enc] = "_utf8enc",
  [sym__utf8line] = "_utf8line",
  [sym__id] = "_id",
  [sym_id] = "id",
  [sym_valtype] = "valtype",
  [sym_functype] = "functype",
  [sym_param] = "param",
  [sym_result] = "result",
  [sym_type] = "type",
  [sym_module] = "module",
  [sym_modulefield] = "modulefield",
  [aux_sym_start_repeat1] = "start_repeat1",
  [aux_sym_linecomment_repeat1] = "linecomment_repeat1",
  [aux_sym_blockcomment_repeat1] = "blockcomment_repeat1",
  [aux_sym__id_repeat1] = "_id_repeat1",
  [aux_sym_functype_repeat1] = "functype_repeat1",
  [aux_sym_functype_repeat2] = "functype_repeat2",
  [aux_sym_param_repeat1] = "param_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [sym__format] = sym__format,
  [anon_sym_SEMI_SEMI] = anon_sym_SEMI_SEMI,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LPAREN_SEMI] = anon_sym_LPAREN_SEMI,
  [anon_sym_SEMI_RPAREN] = anon_sym_SEMI_RPAREN,
  [aux_sym__blockchar_token1] = aux_sym__blockchar_token1,
  [aux_sym__blockchar_token2] = aux_sym__blockchar_token2,
  [aux_sym__blockchar_token3] = aux_sym__blockchar_token3,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_param] = anon_sym_param,
  [anon_sym_result] = anon_sym_result,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_type] = anon_sym_type,
  [sym__sign] = sym__sign,
  [sym__digit] = sym__digit,
  [sym__hexdigit] = sym__hexdigit,
  [anon_sym__] = anon_sym__,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__float_token1] = aux_sym__float_token1,
  [aux_sym__hexfloat_token1] = aux_sym__hexfloat_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym__stringchar_token1] = aux_sym__stringchar_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__char_token1] = aux_sym__char_token1,
  [sym__ascii] = sym__ascii,
  [sym__asciiline] = sym__asciiline,
  [sym__utf8cont] = sym__utf8cont,
  [aux_sym__utf8enc_token1] = aux_sym__utf8enc_token1,
  [aux_sym__utf8enc_token2] = aux_sym__utf8enc_token2,
  [aux_sym__utf8enc_token3] = aux_sym__utf8enc_token3,
  [aux_sym__utf8enc_token4] = aux_sym__utf8enc_token4,
  [aux_sym__utf8enc_token5] = aux_sym__utf8enc_token5,
  [aux_sym__utf8enc_token6] = aux_sym__utf8enc_token6,
  [aux_sym__utf8enc_token7] = aux_sym__utf8enc_token7,
  [aux_sym__utf8enc_token8] = aux_sym__utf8enc_token8,
  [aux_sym__utf8enc_token9] = aux_sym__utf8enc_token9,
  [aux_sym__utf8enc_token10] = aux_sym__utf8enc_token10,
  [aux_sym__utf8enc_token11] = aux_sym__utf8enc_token11,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym__idchar] = sym__idchar,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [sym_start] = sym_start,
  [sym__space] = sym__space,
  [sym__comment] = sym__comment,
  [sym_linecomment] = sym_linecomment,
  [sym__linechar] = sym__linechar,
  [sym_blockcomment] = sym_blockcomment,
  [sym__blockchar] = sym__blockchar,
  [sym__FUNC] = sym__FUNC,
  [sym__LPAR] = sym__LPAR,
  [sym__MODULE] = sym__MODULE,
  [sym__PARAM] = sym__PARAM,
  [sym__RESULT] = sym__RESULT,
  [sym__RPAR] = sym__RPAR,
  [sym__TYPE] = sym__TYPE,
  [sym__utf8enc] = sym__utf8enc,
  [sym__utf8line] = sym__utf8line,
  [sym__id] = sym__id,
  [sym_id] = sym_id,
  [sym_valtype] = sym_valtype,
  [sym_functype] = sym_functype,
  [sym_param] = sym_param,
  [sym_result] = sym_result,
  [sym_type] = sym_type,
  [sym_module] = sym_module,
  [sym_modulefield] = sym_modulefield,
  [aux_sym_start_repeat1] = aux_sym_start_repeat1,
  [aux_sym_linecomment_repeat1] = aux_sym_linecomment_repeat1,
  [aux_sym_blockcomment_repeat1] = aux_sym_blockcomment_repeat1,
  [aux_sym__id_repeat1] = aux_sym__id_repeat1,
  [aux_sym_functype_repeat1] = aux_sym_functype_repeat1,
  [aux_sym_functype_repeat2] = aux_sym_functype_repeat2,
  [aux_sym_param_repeat1] = aux_sym_param_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [sym__format] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__blockchar_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__blockchar_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__blockchar_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_param] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_result] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [sym__sign] = {
    .visible = false,
    .named = true,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [sym__hexdigit] = {
    .visible = false,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hexfloat_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__stringchar_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__char_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__ascii] = {
    .visible = false,
    .named = true,
  },
  [sym__asciiline] = {
    .visible = false,
    .named = true,
  },
  [sym__utf8cont] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__utf8enc_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token7] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token8] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token9] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token10] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__utf8enc_token11] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym__idchar] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [sym_start] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_linecomment] = {
    .visible = true,
    .named = true,
  },
  [sym__linechar] = {
    .visible = false,
    .named = true,
  },
  [sym_blockcomment] = {
    .visible = true,
    .named = true,
  },
  [sym__blockchar] = {
    .visible = false,
    .named = true,
  },
  [sym__FUNC] = {
    .visible = false,
    .named = true,
  },
  [sym__LPAR] = {
    .visible = false,
    .named = true,
  },
  [sym__MODULE] = {
    .visible = false,
    .named = true,
  },
  [sym__PARAM] = {
    .visible = false,
    .named = true,
  },
  [sym__RESULT] = {
    .visible = false,
    .named = true,
  },
  [sym__RPAR] = {
    .visible = false,
    .named = true,
  },
  [sym__TYPE] = {
    .visible = false,
    .named = true,
  },
  [sym__utf8enc] = {
    .visible = false,
    .named = true,
  },
  [sym__utf8line] = {
    .visible = false,
    .named = true,
  },
  [sym__id] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_valtype] = {
    .visible = true,
    .named = true,
  },
  [sym_functype] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_result] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_modulefield] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_start_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_linecomment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blockcomment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__id_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_functype_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_functype_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == '(') ADVANCE(46);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == '.') ADVANCE(54);
      if (lookahead == ';') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '_') ADVANCE(53);
      if (lookahead == '}') ADVANCE(57);
      if (lookahead == 224) ADVANCE(42);
      if (lookahead == 237) ADVANCE(42);
      if (lookahead == 240) ADVANCE(42);
      if (lookahead == 244) ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(37);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(42);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(42);
      if ((241 <= lookahead && lookahead <= 243)) ADVANCE(42);
      if (lookahead == '\'' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(42);
      if (('[' <= lookahead && lookahead <= ']') ||
          lookahead == '`' ||
          lookahead == '{') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (lookahead == 192 ||
          lookahead == 193 ||
          (245 <= lookahead && lookahead <= 255)) ADVANCE(42);
      if ((225 <= lookahead && lookahead <= 239)) ADVANCE(42);
      if ((128 <= lookahead && lookahead <= 143)) ADVANCE(42);
      if ((144 <= lookahead && lookahead <= 159)) ADVANCE(42);
      if ((0 <= lookahead && lookahead <= 31) ||
          lookahead == 127) ADVANCE(42);
      if ((194 <= lookahead && lookahead <= 223)) ADVANCE(42);
      if ((160 <= lookahead && lookahead <= 191)) ADVANCE(42);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == 224) ADVANCE(62);
      if (lookahead == 237) ADVANCE(64);
      if (lookahead == 240) ADVANCE(67);
      if (lookahead == 244) ADVANCE(69);
      if ((241 <= lookahead && lookahead <= 243)) ADVANCE(71);
      if ((225 <= lookahead && lookahead <= 239)) ADVANCE(66);
      if ((194 <= lookahead && lookahead <= 223)) ADVANCE(61);
      if ((128 <= lookahead && lookahead <= 159)) ADVANCE(65);
      if ((160 <= lookahead && lookahead <= 191)) ADVANCE(63);
      if ((0 <= lookahead && lookahead <= 127)) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(37);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= 'Z') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(74);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(37);
      if ((128 <= lookahead && lookahead <= 191)) ADVANCE(60);
      if (lookahead == '!' ||
          ('#' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          lookahead == '\\' ||
          lookahead == '^' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ';') ADVANCE(5);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(41);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == '2') ADVANCE(78);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(76);
      END_STATE();
    case 8:
      if (lookahead == '3') ADVANCE(6);
      if (lookahead == '6') ADVANCE(10);
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '4') ADVANCE(79);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(77);
      END_STATE();
    case 12:
      if (lookahead == ';') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == ';') ADVANCE(40);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 14:
      if (lookahead == ';') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 33:
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(37);
      if ((128 <= lookahead && lookahead <= 143)) ADVANCE(70);
      if ((144 <= lookahead && lookahead <= 191)) ADVANCE(68);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__format);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SEMI_SEMI);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN_SEMI);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SEMI_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__blockchar_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__blockchar_token2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__blockchar_token3);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ';') ADVANCE(40);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_param);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_result);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__char_token1);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__asciiline);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__utf8cont);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__utf8enc_token1);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__utf8enc_token2);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__utf8enc_token3);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__utf8enc_token4);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__utf8enc_token5);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__utf8enc_token6);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__utf8enc_token7);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__utf8enc_token8);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__utf8enc_token9);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__utf8enc_token10);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__utf8enc_token11);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__idchar);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__idchar);
      if (lookahead == '3') ADVANCE(6);
      if (lookahead == '6') ADVANCE(10);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__idchar);
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(11);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 34},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 34},
  [21] = {.lex_state = 34},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 34},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 34},
  [31] = {.lex_state = 34},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 34},
  [34] = {.lex_state = 34},
  [35] = {.lex_state = 34},
  [36] = {.lex_state = 34},
  [37] = {.lex_state = 34},
  [38] = {.lex_state = 34},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 34},
  [41] = {.lex_state = 34},
  [42] = {.lex_state = 34},
  [43] = {.lex_state = 34},
  [44] = {.lex_state = 34},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 34},
  [47] = {.lex_state = 34},
  [48] = {.lex_state = 34},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 34},
  [52] = {.lex_state = 34},
  [53] = {.lex_state = 34},
  [54] = {.lex_state = 34},
  [55] = {.lex_state = 34},
  [56] = {.lex_state = 34},
  [57] = {.lex_state = 34},
  [58] = {.lex_state = 34},
  [59] = {.lex_state = 34},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 34},
  [62] = {.lex_state = 34},
  [63] = {.lex_state = 34},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 34},
  [74] = {.lex_state = 34},
  [75] = {.lex_state = 34},
  [76] = {.lex_state = 34},
  [77] = {.lex_state = 34},
  [78] = {.lex_state = 34},
  [79] = {.lex_state = 34},
  [80] = {.lex_state = 34},
  [81] = {.lex_state = 34},
  [82] = {.lex_state = 34},
  [83] = {.lex_state = 34},
  [84] = {.lex_state = 34},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 34},
  [87] = {.lex_state = 34},
  [88] = {.lex_state = 34},
  [89] = {.lex_state = 34},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 34},
  [92] = {.lex_state = 34},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 34},
  [96] = {.lex_state = 34},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [sym__format] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym__blockchar_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym__sign] = ACTIONS(1),
    [sym__digit] = ACTIONS(1),
    [sym__hexdigit] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym__float_token1] = ACTIONS(1),
    [aux_sym__hexfloat_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym__stringchar_token1] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym__char_token1] = ACTIONS(1),
    [sym__ascii] = ACTIONS(1),
    [sym__asciiline] = ACTIONS(1),
    [sym__utf8cont] = ACTIONS(1),
    [aux_sym__utf8enc_token1] = ACTIONS(1),
    [aux_sym__utf8enc_token2] = ACTIONS(1),
    [aux_sym__utf8enc_token3] = ACTIONS(1),
    [aux_sym__utf8enc_token4] = ACTIONS(1),
    [aux_sym__utf8enc_token5] = ACTIONS(1),
    [aux_sym__utf8enc_token6] = ACTIONS(1),
    [aux_sym__utf8enc_token7] = ACTIONS(1),
    [aux_sym__utf8enc_token8] = ACTIONS(1),
    [aux_sym__utf8enc_token9] = ACTIONS(1),
    [aux_sym__utf8enc_token10] = ACTIONS(1),
    [aux_sym__utf8enc_token11] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym__idchar] = ACTIONS(1),
  },
  [1] = {
    [sym_start] = STATE(102),
    [sym__space] = STATE(57),
    [sym__comment] = STATE(57),
    [sym_linecomment] = STATE(57),
    [sym_blockcomment] = STATE(57),
    [sym__LPAR] = STATE(36),
    [sym_module] = STATE(56),
    [aux_sym_start_repeat1] = STATE(57),
    [anon_sym_] = ACTIONS(3),
    [sym__format] = ACTIONS(3),
    [anon_sym_SEMI_SEMI] = ACTIONS(5),
    [anon_sym_LPAREN_SEMI] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(16), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(19), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(22), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
    ACTIONS(11), 12,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_RPAREN,
      anon_sym_type,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [35] = 11,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(26), 1,
      anon_sym_RPAREN,
    ACTIONS(28), 1,
      anon_sym_DOLLAR,
    STATE(25), 1,
      sym_id,
    STATE(55), 1,
      sym__id,
    STATE(76), 1,
      sym__RPAR,
    ACTIONS(24), 2,
      anon_sym_,
      sym__format,
    STATE(10), 2,
      sym_valtype,
      aux_sym_param_repeat1,
    ACTIONS(30), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(18), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [78] = 13,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    ACTIONS(38), 1,
      anon_sym_DOLLAR,
    STATE(17), 1,
      sym_id,
    STATE(43), 1,
      sym__LPAR,
    STATE(55), 1,
      sym__id,
    STATE(75), 1,
      sym_type,
    STATE(88), 1,
      sym__RPAR,
    ACTIONS(32), 2,
      anon_sym_,
      sym__format,
    STATE(15), 2,
      sym_modulefield,
      aux_sym_module_repeat1,
    STATE(30), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [124] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(42), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym__RPAR,
    ACTIONS(40), 2,
      anon_sym_,
      sym__format,
    STATE(6), 2,
      sym_valtype,
      aux_sym_param_repeat1,
    ACTIONS(30), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(26), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [158] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(44), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym__RPAR,
    ACTIONS(40), 2,
      anon_sym_,
      sym__format,
    STATE(16), 2,
      sym_valtype,
      aux_sym_param_repeat1,
    ACTIONS(30), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(26), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [192] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym__LPAR,
    STATE(87), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(9), 2,
      sym_param,
      aux_sym_functype_repeat1,
    STATE(22), 2,
      sym_result,
      aux_sym_functype_repeat2,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [230] = 2,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 16,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_RPAREN,
      anon_sym_type,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [252] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym__LPAR,
    STATE(86), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(20), 2,
      sym_result,
      aux_sym_functype_repeat2,
    STATE(24), 2,
      sym_param,
      aux_sym_functype_repeat1,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [290] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym__RPAR,
    ACTIONS(40), 2,
      anon_sym_,
      sym__format,
    STATE(16), 2,
      sym_valtype,
      aux_sym_param_repeat1,
    ACTIONS(30), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(26), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [324] = 2,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 16,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_RPAREN,
      anon_sym_type,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [346] = 2,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 16,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_RPAREN,
      anon_sym_type,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [368] = 2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 16,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_RPAREN,
      anon_sym_type,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [390] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__LPAR,
    STATE(75), 1,
      sym_type,
    STATE(92), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(21), 2,
      sym_modulefield,
      aux_sym_module_repeat1,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [427] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__LPAR,
    STATE(75), 1,
      sym_type,
    STATE(89), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(21), 2,
      sym_modulefield,
      aux_sym_module_repeat1,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [464] = 7,
    ACTIONS(79), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(82), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(76), 2,
      anon_sym_,
      sym__format,
    STATE(16), 2,
      sym_valtype,
      aux_sym_param_repeat1,
    ACTIONS(87), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(27), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [495] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__LPAR,
    STATE(75), 1,
      sym_type,
    STATE(89), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(14), 2,
      sym_modulefield,
      aux_sym_module_repeat1,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [532] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(28), 1,
      anon_sym_DOLLAR,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym__id,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    ACTIONS(94), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [565] = 10,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(38), 1,
      anon_sym_DOLLAR,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_id,
    STATE(37), 1,
      sym_functype,
    STATE(38), 1,
      sym__LPAR,
    STATE(55), 1,
      sym__id,
    ACTIONS(96), 2,
      anon_sym_,
      sym__format,
    STATE(33), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [601] = 9,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      sym__LPAR,
    STATE(91), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(23), 2,
      sym_result,
      aux_sym_functype_repeat2,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [635] = 9,
    ACTIONS(107), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(110), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__LPAR,
    STATE(75), 1,
      sym_type,
    ACTIONS(104), 2,
      anon_sym_,
      sym__format,
    STATE(21), 2,
      sym_modulefield,
      aux_sym_module_repeat1,
    STATE(57), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [669] = 9,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(100), 1,
      anon_sym_LPAREN,
    STATE(35), 1,
      sym__LPAR,
    STATE(86), 1,
      sym__RPAR,
    ACTIONS(46), 2,
      anon_sym_,
      sym__format,
    STATE(23), 2,
      sym_result,
      aux_sym_functype_repeat2,
    STATE(44), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [703] = 8,
    ACTIONS(121), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(124), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      sym__LPAR,
    ACTIONS(118), 2,
      anon_sym_,
      sym__format,
    STATE(23), 2,
      sym_result,
      aux_sym_functype_repeat2,
    STATE(57), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [734] = 8,
    ACTIONS(135), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(138), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym__LPAR,
    ACTIONS(132), 2,
      anon_sym_,
      sym__format,
    STATE(24), 2,
      sym_param,
      aux_sym_functype_repeat1,
    STATE(57), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [765] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    STATE(39), 1,
      sym_valtype,
    ACTIONS(146), 2,
      anon_sym_,
      sym__format,
    ACTIONS(30), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(27), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [792] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    ACTIONS(94), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [819] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    ACTIONS(94), 4,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [843] = 10,
    ACTIONS(148), 1,
      anon_sym_LF,
    ACTIONS(150), 1,
      sym__asciiline,
    ACTIONS(152), 1,
      aux_sym__utf8enc_token1,
    ACTIONS(154), 1,
      aux_sym__utf8enc_token2,
    ACTIONS(156), 1,
      aux_sym__utf8enc_token4,
    ACTIONS(158), 1,
      aux_sym__utf8enc_token6,
    ACTIONS(160), 1,
      aux_sym__utf8enc_token7,
    ACTIONS(162), 1,
      aux_sym__utf8enc_token9,
    ACTIONS(164), 1,
      aux_sym__utf8enc_token11,
    STATE(32), 4,
      sym__linechar,
      sym__utf8enc,
      sym__utf8line,
      aux_sym_linecomment_repeat1,
  [877] = 10,
    ACTIONS(166), 1,
      anon_sym_LF,
    ACTIONS(168), 1,
      sym__asciiline,
    ACTIONS(171), 1,
      aux_sym__utf8enc_token1,
    ACTIONS(174), 1,
      aux_sym__utf8enc_token2,
    ACTIONS(177), 1,
      aux_sym__utf8enc_token4,
    ACTIONS(180), 1,
      aux_sym__utf8enc_token6,
    ACTIONS(183), 1,
      aux_sym__utf8enc_token7,
    ACTIONS(186), 1,
      aux_sym__utf8enc_token9,
    ACTIONS(189), 1,
      aux_sym__utf8enc_token11,
    STATE(29), 4,
      sym__linechar,
      sym__utf8enc,
      sym__utf8line,
      aux_sym_linecomment_repeat1,
  [911] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(38), 1,
      anon_sym_DOLLAR,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(192), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym__id,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [941] = 8,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(196), 1,
      anon_sym_param,
    ACTIONS(198), 1,
      anon_sym_result,
    STATE(3), 1,
      sym__PARAM,
    STATE(5), 1,
      sym__RESULT,
    ACTIONS(194), 2,
      anon_sym_,
      sym__format,
    STATE(41), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [971] = 10,
    ACTIONS(152), 1,
      aux_sym__utf8enc_token1,
    ACTIONS(154), 1,
      aux_sym__utf8enc_token2,
    ACTIONS(156), 1,
      aux_sym__utf8enc_token4,
    ACTIONS(158), 1,
      aux_sym__utf8enc_token6,
    ACTIONS(160), 1,
      aux_sym__utf8enc_token7,
    ACTIONS(162), 1,
      aux_sym__utf8enc_token9,
    ACTIONS(164), 1,
      aux_sym__utf8enc_token11,
    ACTIONS(200), 1,
      anon_sym_LF,
    ACTIONS(202), 1,
      sym__asciiline,
    STATE(29), 4,
      sym__linechar,
      sym__utf8enc,
      sym__utf8line,
      aux_sym_linecomment_repeat1,
  [1005] = 7,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(38), 1,
      anon_sym_DOLLAR,
    ACTIONS(192), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym__id,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1032] = 7,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym__LPAR,
    STATE(42), 1,
      sym_functype,
    ACTIONS(3), 2,
      anon_sym_,
      sym__format,
    STATE(57), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1059] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(198), 1,
      anon_sym_result,
    STATE(5), 1,
      sym__RESULT,
    ACTIONS(204), 2,
      anon_sym_,
      sym__format,
    STATE(53), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1083] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(208), 1,
      anon_sym_module,
    STATE(4), 1,
      sym__MODULE,
    ACTIONS(206), 2,
      anon_sym_,
      sym__format,
    STATE(48), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1107] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym__RPAR,
    ACTIONS(210), 2,
      anon_sym_,
      sym__format,
    STATE(52), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1131] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(216), 1,
      anon_sym_func,
    STATE(7), 1,
      sym__FUNC,
    ACTIONS(214), 2,
      anon_sym_,
      sym__format,
    STATE(58), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1155] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym__RPAR,
    ACTIONS(210), 2,
      anon_sym_,
      sym__format,
    STATE(52), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1179] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(196), 1,
      anon_sym_param,
    STATE(3), 1,
      sym__PARAM,
    ACTIONS(220), 2,
      anon_sym_,
      sym__format,
    STATE(47), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1203] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(222), 1,
      anon_sym_param,
    ACTIONS(224), 1,
      anon_sym_result,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1227] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym__RPAR,
    ACTIONS(210), 2,
      anon_sym_,
      sym__format,
    STATE(52), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1251] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(230), 1,
      anon_sym_type,
    STATE(19), 1,
      sym__TYPE,
    ACTIONS(228), 2,
      anon_sym_,
      sym__format,
    STATE(46), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1275] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(192), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1299] = 3,
    ACTIONS(234), 1,
      sym__idchar,
    STATE(45), 1,
      aux_sym__id_repeat1,
    ACTIONS(232), 8,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1316] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(237), 1,
      anon_sym_type,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1337] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(222), 1,
      anon_sym_param,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1358] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(239), 1,
      anon_sym_module,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1379] = 2,
    ACTIONS(243), 1,
      anon_sym_LPAREN,
    ACTIONS(241), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1394] = 3,
    ACTIONS(247), 1,
      sym__idchar,
    STATE(45), 1,
      aux_sym__id_repeat1,
    ACTIONS(245), 8,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1411] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1432] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1453] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(224), 1,
      anon_sym_result,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1474] = 1,
    ACTIONS(251), 10,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1487] = 2,
    ACTIONS(255), 1,
      anon_sym_LPAREN,
    ACTIONS(253), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1502] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(259), 2,
      anon_sym_,
      sym__format,
    STATE(51), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1523] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(192), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1544] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI_SEMI,
    ACTIONS(7), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(261), 1,
      anon_sym_func,
    ACTIONS(90), 2,
      anon_sym_,
      sym__format,
    STATE(2), 5,
      sym__space,
      sym__comment,
      sym_linecomment,
      sym_blockcomment,
      aux_sym_start_repeat1,
  [1565] = 1,
    ACTIONS(263), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1577] = 1,
    ACTIONS(265), 9,
      anon_sym_LF,
      sym__asciiline,
      aux_sym__utf8enc_token1,
      aux_sym__utf8enc_token2,
      aux_sym__utf8enc_token4,
      aux_sym__utf8enc_token6,
      aux_sym__utf8enc_token7,
      aux_sym__utf8enc_token9,
      aux_sym__utf8enc_token11,
  [1589] = 1,
    ACTIONS(267), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1601] = 1,
    ACTIONS(269), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_f32,
      anon_sym_f64,
  [1613] = 1,
    ACTIONS(271), 9,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_func,
      anon_sym_module,
      anon_sym_param,
      anon_sym_result,
      anon_sym_type,
  [1625] = 1,
    ACTIONS(273), 9,
      anon_sym_LF,
      sym__asciiline,
      aux_sym__utf8enc_token1,
      aux_sym__utf8enc_token2,
      aux_sym__utf8enc_token4,
      aux_sym__utf8enc_token6,
      aux_sym__utf8enc_token7,
      aux_sym__utf8enc_token9,
      aux_sym__utf8enc_token11,
  [1637] = 1,
    ACTIONS(275), 9,
      anon_sym_LF,
      sym__asciiline,
      aux_sym__utf8enc_token1,
      aux_sym__utf8enc_token2,
      aux_sym__utf8enc_token4,
      aux_sym__utf8enc_token6,
      aux_sym__utf8enc_token7,
      aux_sym__utf8enc_token9,
      aux_sym__utf8enc_token11,
  [1649] = 4,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(279), 1,
      sym__idchar,
    STATE(72), 1,
      aux_sym__id_repeat1,
    ACTIONS(245), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1666] = 4,
    ACTIONS(281), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(283), 1,
      anon_sym_SEMI_RPAREN,
    ACTIONS(285), 3,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
    STATE(71), 3,
      sym_blockcomment,
      sym__blockchar,
      aux_sym_blockcomment_repeat1,
  [1683] = 4,
    ACTIONS(281), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(287), 1,
      anon_sym_SEMI_RPAREN,
    ACTIONS(289), 3,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
    STATE(67), 3,
      sym_blockcomment,
      sym__blockchar,
      aux_sym_blockcomment_repeat1,
  [1700] = 4,
    ACTIONS(281), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(291), 1,
      anon_sym_SEMI_RPAREN,
    ACTIONS(293), 3,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
    STATE(70), 3,
      sym_blockcomment,
      sym__blockchar,
      aux_sym_blockcomment_repeat1,
  [1717] = 4,
    ACTIONS(281), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(295), 1,
      anon_sym_SEMI_RPAREN,
    ACTIONS(285), 3,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
    STATE(71), 3,
      sym_blockcomment,
      sym__blockchar,
      aux_sym_blockcomment_repeat1,
  [1734] = 4,
    ACTIONS(297), 1,
      anon_sym_LPAREN_SEMI,
    ACTIONS(300), 1,
      anon_sym_SEMI_RPAREN,
    ACTIONS(302), 3,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
    STATE(71), 3,
      sym_blockcomment,
      sym__blockchar,
      aux_sym_blockcomment_repeat1,
  [1751] = 4,
    ACTIONS(305), 1,
      anon_sym_LPAREN,
    ACTIONS(307), 1,
      sym__idchar,
    STATE(72), 1,
      aux_sym__id_repeat1,
    ACTIONS(232), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1768] = 2,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
    ACTIONS(310), 6,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
  [1780] = 2,
    ACTIONS(316), 1,
      anon_sym_LPAREN,
    ACTIONS(314), 6,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1792] = 2,
    ACTIONS(320), 1,
      anon_sym_LPAREN,
    ACTIONS(318), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1803] = 2,
    ACTIONS(324), 1,
      anon_sym_LPAREN,
    ACTIONS(322), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1814] = 2,
    ACTIONS(328), 1,
      anon_sym_LPAREN,
    ACTIONS(326), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1825] = 2,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
    ACTIONS(330), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1836] = 2,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
    ACTIONS(334), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_DOLLAR,
  [1847] = 2,
    ACTIONS(340), 1,
      anon_sym_LPAREN,
    ACTIONS(338), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1858] = 2,
    ACTIONS(344), 1,
      anon_sym_LPAREN,
    ACTIONS(342), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1869] = 2,
    ACTIONS(348), 1,
      anon_sym_LPAREN,
    ACTIONS(346), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1880] = 2,
    ACTIONS(352), 1,
      anon_sym_LPAREN,
    ACTIONS(350), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1891] = 2,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
    ACTIONS(354), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1902] = 1,
    ACTIONS(68), 5,
      anon_sym_LPAREN_SEMI,
      anon_sym_SEMI_RPAREN,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
  [1910] = 1,
    ACTIONS(358), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1918] = 1,
    ACTIONS(360), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1926] = 1,
    ACTIONS(362), 5,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
  [1934] = 1,
    ACTIONS(364), 5,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
  [1942] = 1,
    ACTIONS(60), 5,
      anon_sym_LPAREN_SEMI,
      anon_sym_SEMI_RPAREN,
      aux_sym__blockchar_token1,
      aux_sym__blockchar_token2,
      aux_sym__blockchar_token3,
  [1950] = 1,
    ACTIONS(366), 5,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
      anon_sym_RPAREN,
  [1958] = 1,
    ACTIONS(368), 5,
      ts_builtin_sym_end,
      anon_sym_,
      sym__format,
      anon_sym_SEMI_SEMI,
      anon_sym_LPAREN_SEMI,
  [1966] = 2,
    ACTIONS(370), 1,
      sym__idchar,
    STATE(50), 1,
      aux_sym__id_repeat1,
  [1973] = 2,
    ACTIONS(372), 1,
      sym__idchar,
    STATE(66), 1,
      aux_sym__id_repeat1,
  [1980] = 1,
    ACTIONS(374), 1,
      aux_sym__utf8enc_token10,
  [1984] = 1,
    ACTIONS(374), 1,
      aux_sym__utf8enc_token8,
  [1988] = 1,
    ACTIONS(376), 1,
      aux_sym__utf8enc_token3,
  [1992] = 1,
    ACTIONS(376), 1,
      sym__utf8cont,
  [1996] = 1,
    ACTIONS(376), 1,
      aux_sym__utf8enc_token5,
  [2000] = 1,
    ACTIONS(378), 1,
      sym__utf8cont,
  [2004] = 1,
    ACTIONS(380), 1,
      sym__utf8cont,
  [2008] = 1,
    ACTIONS(382), 1,
      ts_builtin_sym_end,
  [2012] = 1,
    ACTIONS(374), 1,
      sym__utf8cont,
  [2016] = 1,
    ACTIONS(384), 1,
      sym__utf8cont,
  [2020] = 1,
    ACTIONS(386), 1,
      sym__utf8cont,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 124,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 192,
  [SMALL_STATE(8)] = 230,
  [SMALL_STATE(9)] = 252,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 324,
  [SMALL_STATE(12)] = 346,
  [SMALL_STATE(13)] = 368,
  [SMALL_STATE(14)] = 390,
  [SMALL_STATE(15)] = 427,
  [SMALL_STATE(16)] = 464,
  [SMALL_STATE(17)] = 495,
  [SMALL_STATE(18)] = 532,
  [SMALL_STATE(19)] = 565,
  [SMALL_STATE(20)] = 601,
  [SMALL_STATE(21)] = 635,
  [SMALL_STATE(22)] = 669,
  [SMALL_STATE(23)] = 703,
  [SMALL_STATE(24)] = 734,
  [SMALL_STATE(25)] = 765,
  [SMALL_STATE(26)] = 792,
  [SMALL_STATE(27)] = 819,
  [SMALL_STATE(28)] = 843,
  [SMALL_STATE(29)] = 877,
  [SMALL_STATE(30)] = 911,
  [SMALL_STATE(31)] = 941,
  [SMALL_STATE(32)] = 971,
  [SMALL_STATE(33)] = 1005,
  [SMALL_STATE(34)] = 1032,
  [SMALL_STATE(35)] = 1059,
  [SMALL_STATE(36)] = 1083,
  [SMALL_STATE(37)] = 1107,
  [SMALL_STATE(38)] = 1131,
  [SMALL_STATE(39)] = 1155,
  [SMALL_STATE(40)] = 1179,
  [SMALL_STATE(41)] = 1203,
  [SMALL_STATE(42)] = 1227,
  [SMALL_STATE(43)] = 1251,
  [SMALL_STATE(44)] = 1275,
  [SMALL_STATE(45)] = 1299,
  [SMALL_STATE(46)] = 1316,
  [SMALL_STATE(47)] = 1337,
  [SMALL_STATE(48)] = 1358,
  [SMALL_STATE(49)] = 1379,
  [SMALL_STATE(50)] = 1394,
  [SMALL_STATE(51)] = 1411,
  [SMALL_STATE(52)] = 1432,
  [SMALL_STATE(53)] = 1453,
  [SMALL_STATE(54)] = 1474,
  [SMALL_STATE(55)] = 1487,
  [SMALL_STATE(56)] = 1502,
  [SMALL_STATE(57)] = 1523,
  [SMALL_STATE(58)] = 1544,
  [SMALL_STATE(59)] = 1565,
  [SMALL_STATE(60)] = 1577,
  [SMALL_STATE(61)] = 1589,
  [SMALL_STATE(62)] = 1601,
  [SMALL_STATE(63)] = 1613,
  [SMALL_STATE(64)] = 1625,
  [SMALL_STATE(65)] = 1637,
  [SMALL_STATE(66)] = 1649,
  [SMALL_STATE(67)] = 1666,
  [SMALL_STATE(68)] = 1683,
  [SMALL_STATE(69)] = 1700,
  [SMALL_STATE(70)] = 1717,
  [SMALL_STATE(71)] = 1734,
  [SMALL_STATE(72)] = 1751,
  [SMALL_STATE(73)] = 1768,
  [SMALL_STATE(74)] = 1780,
  [SMALL_STATE(75)] = 1792,
  [SMALL_STATE(76)] = 1803,
  [SMALL_STATE(77)] = 1814,
  [SMALL_STATE(78)] = 1825,
  [SMALL_STATE(79)] = 1836,
  [SMALL_STATE(80)] = 1847,
  [SMALL_STATE(81)] = 1858,
  [SMALL_STATE(82)] = 1869,
  [SMALL_STATE(83)] = 1880,
  [SMALL_STATE(84)] = 1891,
  [SMALL_STATE(85)] = 1902,
  [SMALL_STATE(86)] = 1910,
  [SMALL_STATE(87)] = 1918,
  [SMALL_STATE(88)] = 1926,
  [SMALL_STATE(89)] = 1934,
  [SMALL_STATE(90)] = 1942,
  [SMALL_STATE(91)] = 1950,
  [SMALL_STATE(92)] = 1958,
  [SMALL_STATE(93)] = 1966,
  [SMALL_STATE(94)] = 1973,
  [SMALL_STATE(95)] = 1980,
  [SMALL_STATE(96)] = 1984,
  [SMALL_STATE(97)] = 1988,
  [SMALL_STATE(98)] = 1992,
  [SMALL_STATE(99)] = 1996,
  [SMALL_STATE(100)] = 2000,
  [SMALL_STATE(101)] = 2004,
  [SMALL_STATE(102)] = 2008,
  [SMALL_STATE(103)] = 2012,
  [SMALL_STATE(104)] = 2016,
  [SMALL_STATE(105)] = 2020,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, SHIFT(57),
  [5] = {.count = 1, .reusable = true}, SHIFT(28),
  [7] = {.count = 1, .reusable = true}, SHIFT(69),
  [9] = {.count = 1, .reusable = false}, SHIFT(36),
  [11] = {.count = 1, .reusable = true}, REDUCE(aux_sym_start_repeat1, 2),
  [13] = {.count = 2, .reusable = true}, REDUCE(aux_sym_start_repeat1, 2), SHIFT_REPEAT(2),
  [16] = {.count = 2, .reusable = true}, REDUCE(aux_sym_start_repeat1, 2), SHIFT_REPEAT(28),
  [19] = {.count = 2, .reusable = true}, REDUCE(aux_sym_start_repeat1, 2), SHIFT_REPEAT(69),
  [22] = {.count = 1, .reusable = false}, REDUCE(aux_sym_start_repeat1, 2),
  [24] = {.count = 1, .reusable = true}, SHIFT(18),
  [26] = {.count = 1, .reusable = true}, SHIFT(76),
  [28] = {.count = 1, .reusable = true}, SHIFT(93),
  [30] = {.count = 1, .reusable = true}, SHIFT(59),
  [32] = {.count = 1, .reusable = true}, SHIFT(30),
  [34] = {.count = 1, .reusable = false}, SHIFT(43),
  [36] = {.count = 1, .reusable = true}, SHIFT(88),
  [38] = {.count = 1, .reusable = true}, SHIFT(94),
  [40] = {.count = 1, .reusable = true}, SHIFT(26),
  [42] = {.count = 1, .reusable = true}, SHIFT(78),
  [44] = {.count = 1, .reusable = true}, SHIFT(83),
  [46] = {.count = 1, .reusable = true}, SHIFT(44),
  [48] = {.count = 1, .reusable = false}, SHIFT(31),
  [50] = {.count = 1, .reusable = true}, SHIFT(87),
  [52] = {.count = 1, .reusable = true}, REDUCE(sym_linecomment, 2),
  [54] = {.count = 1, .reusable = false}, REDUCE(sym_linecomment, 2),
  [56] = {.count = 1, .reusable = true}, SHIFT(86),
  [58] = {.count = 1, .reusable = true}, SHIFT(82),
  [60] = {.count = 1, .reusable = true}, REDUCE(sym_blockcomment, 3),
  [62] = {.count = 1, .reusable = false}, REDUCE(sym_blockcomment, 3),
  [64] = {.count = 1, .reusable = true}, REDUCE(sym_linecomment, 3),
  [66] = {.count = 1, .reusable = false}, REDUCE(sym_linecomment, 3),
  [68] = {.count = 1, .reusable = true}, REDUCE(sym_blockcomment, 2),
  [70] = {.count = 1, .reusable = false}, REDUCE(sym_blockcomment, 2),
  [72] = {.count = 1, .reusable = true}, SHIFT(92),
  [74] = {.count = 1, .reusable = true}, SHIFT(89),
  [76] = {.count = 2, .reusable = true}, REDUCE(aux_sym_param_repeat1, 2), SHIFT_REPEAT(27),
  [79] = {.count = 2, .reusable = true}, REDUCE(aux_sym_param_repeat1, 2), SHIFT_REPEAT(28),
  [82] = {.count = 2, .reusable = true}, REDUCE(aux_sym_param_repeat1, 2), SHIFT_REPEAT(69),
  [85] = {.count = 1, .reusable = true}, REDUCE(aux_sym_param_repeat1, 2),
  [87] = {.count = 2, .reusable = true}, REDUCE(aux_sym_param_repeat1, 2), SHIFT_REPEAT(59),
  [90] = {.count = 1, .reusable = true}, SHIFT(2),
  [92] = {.count = 1, .reusable = true}, SHIFT(74),
  [94] = {.count = 1, .reusable = true}, SHIFT(61),
  [96] = {.count = 1, .reusable = true}, SHIFT(33),
  [98] = {.count = 1, .reusable = false}, SHIFT(38),
  [100] = {.count = 1, .reusable = false}, SHIFT(35),
  [102] = {.count = 1, .reusable = true}, SHIFT(91),
  [104] = {.count = 2, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(57),
  [107] = {.count = 2, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(28),
  [110] = {.count = 2, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(69),
  [113] = {.count = 2, .reusable = false}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(43),
  [116] = {.count = 1, .reusable = true}, REDUCE(aux_sym_module_repeat1, 2),
  [118] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat2, 2), SHIFT_REPEAT(57),
  [121] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat2, 2), SHIFT_REPEAT(28),
  [124] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat2, 2), SHIFT_REPEAT(69),
  [127] = {.count = 2, .reusable = false}, REDUCE(aux_sym_functype_repeat2, 2), SHIFT_REPEAT(35),
  [130] = {.count = 1, .reusable = true}, REDUCE(aux_sym_functype_repeat2, 2),
  [132] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat1, 2), SHIFT_REPEAT(57),
  [135] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat1, 2), SHIFT_REPEAT(28),
  [138] = {.count = 2, .reusable = true}, REDUCE(aux_sym_functype_repeat1, 2), SHIFT_REPEAT(69),
  [141] = {.count = 2, .reusable = false}, REDUCE(aux_sym_functype_repeat1, 2), SHIFT_REPEAT(40),
  [144] = {.count = 1, .reusable = true}, REDUCE(aux_sym_functype_repeat1, 2),
  [146] = {.count = 1, .reusable = true}, SHIFT(27),
  [148] = {.count = 1, .reusable = true}, SHIFT(8),
  [150] = {.count = 1, .reusable = true}, SHIFT(32),
  [152] = {.count = 1, .reusable = true}, SHIFT(101),
  [154] = {.count = 1, .reusable = true}, SHIFT(97),
  [156] = {.count = 1, .reusable = true}, SHIFT(99),
  [158] = {.count = 1, .reusable = true}, SHIFT(98),
  [160] = {.count = 1, .reusable = true}, SHIFT(96),
  [162] = {.count = 1, .reusable = true}, SHIFT(95),
  [164] = {.count = 1, .reusable = true}, SHIFT(103),
  [166] = {.count = 1, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2),
  [168] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(29),
  [171] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(101),
  [174] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(97),
  [177] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(99),
  [180] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(98),
  [183] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(96),
  [186] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(95),
  [189] = {.count = 2, .reusable = true}, REDUCE(aux_sym_linecomment_repeat1, 2), SHIFT_REPEAT(103),
  [192] = {.count = 1, .reusable = false}, SHIFT(63),
  [194] = {.count = 1, .reusable = true}, SHIFT(41),
  [196] = {.count = 1, .reusable = true}, SHIFT(3),
  [198] = {.count = 1, .reusable = true}, SHIFT(5),
  [200] = {.count = 1, .reusable = true}, SHIFT(12),
  [202] = {.count = 1, .reusable = true}, SHIFT(29),
  [204] = {.count = 1, .reusable = true}, SHIFT(53),
  [206] = {.count = 1, .reusable = true}, SHIFT(48),
  [208] = {.count = 1, .reusable = true}, SHIFT(4),
  [210] = {.count = 1, .reusable = true}, SHIFT(52),
  [212] = {.count = 1, .reusable = true}, SHIFT(81),
  [214] = {.count = 1, .reusable = true}, SHIFT(58),
  [216] = {.count = 1, .reusable = true}, SHIFT(7),
  [218] = {.count = 1, .reusable = true}, SHIFT(84),
  [220] = {.count = 1, .reusable = true}, SHIFT(47),
  [222] = {.count = 1, .reusable = true}, SHIFT(54),
  [224] = {.count = 1, .reusable = true}, SHIFT(62),
  [226] = {.count = 1, .reusable = true}, SHIFT(77),
  [228] = {.count = 1, .reusable = true}, SHIFT(46),
  [230] = {.count = 1, .reusable = true}, SHIFT(19),
  [232] = {.count = 1, .reusable = true}, REDUCE(aux_sym__id_repeat1, 2),
  [234] = {.count = 2, .reusable = false}, REDUCE(aux_sym__id_repeat1, 2), SHIFT_REPEAT(45),
  [237] = {.count = 1, .reusable = true}, SHIFT(79),
  [239] = {.count = 1, .reusable = true}, SHIFT(73),
  [241] = {.count = 1, .reusable = true}, REDUCE(sym_id, 2),
  [243] = {.count = 1, .reusable = false}, REDUCE(sym_id, 2),
  [245] = {.count = 1, .reusable = true}, REDUCE(sym__id, 2),
  [247] = {.count = 1, .reusable = false}, SHIFT(45),
  [249] = {.count = 1, .reusable = true}, REDUCE(sym_start, 2),
  [251] = {.count = 1, .reusable = true}, REDUCE(sym__PARAM, 2),
  [253] = {.count = 1, .reusable = true}, REDUCE(sym_id, 1),
  [255] = {.count = 1, .reusable = false}, REDUCE(sym_id, 1),
  [257] = {.count = 1, .reusable = true}, REDUCE(sym_start, 1),
  [259] = {.count = 1, .reusable = true}, SHIFT(51),
  [261] = {.count = 1, .reusable = true}, SHIFT(80),
  [263] = {.count = 1, .reusable = true}, REDUCE(sym_valtype, 1),
  [265] = {.count = 1, .reusable = true}, REDUCE(sym__utf8enc, 4),
  [267] = {.count = 1, .reusable = true}, REDUCE(sym_valtype, 2),
  [269] = {.count = 1, .reusable = true}, REDUCE(sym__RESULT, 2),
  [271] = {.count = 1, .reusable = true}, REDUCE(sym__LPAR, 2),
  [273] = {.count = 1, .reusable = true}, REDUCE(sym__utf8enc, 2),
  [275] = {.count = 1, .reusable = true}, REDUCE(sym__utf8enc, 3),
  [277] = {.count = 1, .reusable = false}, REDUCE(sym__id, 2),
  [279] = {.count = 1, .reusable = true}, SHIFT(72),
  [281] = {.count = 1, .reusable = true}, SHIFT(68),
  [283] = {.count = 1, .reusable = true}, SHIFT(90),
  [285] = {.count = 1, .reusable = true}, SHIFT(71),
  [287] = {.count = 1, .reusable = true}, SHIFT(85),
  [289] = {.count = 1, .reusable = true}, SHIFT(67),
  [291] = {.count = 1, .reusable = true}, SHIFT(13),
  [293] = {.count = 1, .reusable = true}, SHIFT(70),
  [295] = {.count = 1, .reusable = true}, SHIFT(11),
  [297] = {.count = 2, .reusable = true}, REDUCE(aux_sym_blockcomment_repeat1, 2), SHIFT_REPEAT(68),
  [300] = {.count = 1, .reusable = true}, REDUCE(aux_sym_blockcomment_repeat1, 2),
  [302] = {.count = 2, .reusable = true}, REDUCE(aux_sym_blockcomment_repeat1, 2), SHIFT_REPEAT(71),
  [305] = {.count = 1, .reusable = false}, REDUCE(aux_sym__id_repeat1, 2),
  [307] = {.count = 2, .reusable = true}, REDUCE(aux_sym__id_repeat1, 2), SHIFT_REPEAT(72),
  [310] = {.count = 1, .reusable = true}, REDUCE(sym__MODULE, 2),
  [312] = {.count = 1, .reusable = false}, REDUCE(sym__MODULE, 2),
  [314] = {.count = 1, .reusable = true}, REDUCE(sym__RPAR, 2),
  [316] = {.count = 1, .reusable = false}, REDUCE(sym__RPAR, 2),
  [318] = {.count = 1, .reusable = true}, REDUCE(sym_modulefield, 1),
  [320] = {.count = 1, .reusable = false}, REDUCE(sym_modulefield, 1),
  [322] = {.count = 1, .reusable = true}, REDUCE(sym_param, 3),
  [324] = {.count = 1, .reusable = false}, REDUCE(sym_param, 3),
  [326] = {.count = 1, .reusable = true}, REDUCE(sym_type, 5),
  [328] = {.count = 1, .reusable = false}, REDUCE(sym_type, 5),
  [330] = {.count = 1, .reusable = true}, REDUCE(sym_result, 3),
  [332] = {.count = 1, .reusable = false}, REDUCE(sym_result, 3),
  [334] = {.count = 1, .reusable = true}, REDUCE(sym__TYPE, 2),
  [336] = {.count = 1, .reusable = false}, REDUCE(sym__TYPE, 2),
  [338] = {.count = 1, .reusable = true}, REDUCE(sym__FUNC, 2),
  [340] = {.count = 1, .reusable = false}, REDUCE(sym__FUNC, 2),
  [342] = {.count = 1, .reusable = true}, REDUCE(sym_type, 4),
  [344] = {.count = 1, .reusable = false}, REDUCE(sym_type, 4),
  [346] = {.count = 1, .reusable = true}, REDUCE(sym_param, 4),
  [348] = {.count = 1, .reusable = false}, REDUCE(sym_param, 4),
  [350] = {.count = 1, .reusable = true}, REDUCE(sym_result, 4),
  [352] = {.count = 1, .reusable = false}, REDUCE(sym_result, 4),
  [354] = {.count = 1, .reusable = true}, REDUCE(sym_param, 5),
  [356] = {.count = 1, .reusable = false}, REDUCE(sym_param, 5),
  [358] = {.count = 1, .reusable = true}, REDUCE(sym_functype, 4),
  [360] = {.count = 1, .reusable = true}, REDUCE(sym_functype, 3),
  [362] = {.count = 1, .reusable = true}, REDUCE(sym_module, 3),
  [364] = {.count = 1, .reusable = true}, REDUCE(sym_module, 4),
  [366] = {.count = 1, .reusable = true}, REDUCE(sym_functype, 5),
  [368] = {.count = 1, .reusable = true}, REDUCE(sym_module, 5),
  [370] = {.count = 1, .reusable = true}, SHIFT(50),
  [372] = {.count = 1, .reusable = true}, SHIFT(66),
  [374] = {.count = 1, .reusable = true}, SHIFT(105),
  [376] = {.count = 1, .reusable = true}, SHIFT(104),
  [378] = {.count = 1, .reusable = true}, SHIFT(60),
  [380] = {.count = 1, .reusable = true}, SHIFT(64),
  [382] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
  [384] = {.count = 1, .reusable = true}, SHIFT(65),
  [386] = {.count = 1, .reusable = true}, SHIFT(100),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_wast(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
